from unrealsdk import make_struct, find_object#type:ignore


resource_data = [
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Combat_Rifle'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Combat_Rifle_Pool'),Amount=560.000000,UpgradeLevel=2),
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Combat_Laser'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Combat_Laser_Pool'),Amount=740.000000,UpgradeLevel=2),
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Combat_Shotgun'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Combat_Shotgun_Pool'),Amount=120.000000,UpgradeLevel=2),
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Grenade_Protean'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Grenade_Protean_Pool'),Amount=5.000000,UpgradeLevel=2),
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Patrol_SMG'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Patrol_SMG_Pool'),Amount=720.000000,UpgradeLevel=2),
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Repeater_Pistol'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Repeater_Pistol_Pool'),Amount=400.000000,UpgradeLevel=2),
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Rocket_Launcher'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Rocket_Launcher_Pool'),Amount=18.000000,UpgradeLevel=2),
make_struct("ResourceSaveGameData",ResourceDefinition=find_object('ResourceDefinition','D_Resources.AmmoResources.Ammo_Sniper_Rifle'),ResourcePoolDefinition=find_object('ResourcePoolDefinition','D_Resourcepools.AmmoPools.Ammo_Sniper_Rifle_Pool'),Amount=108.000000,UpgradeLevel=2),
]

pt_data = make_struct("MissionPlaythroughSaveGameData",
        MissionData = [
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_Chapter01.M_CH01a_MoonShot'), Status = 4, ObjectivesProgress = [1, 1, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_Chapter01.M_CH01a_MoonShot:ReadyForTurninSet'), SubObjectiveSets = [], GameStage = 1, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_Chapter01.M_CH01b_MoonShot'), Status = 4, ObjectivesProgress = [0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 4, 2], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_Chapter01.M_CH01b_MoonShot:GetOzKitandKillKraggons'), SubObjectiveSets = [], GameStage = 1, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_Chapter02.M_CH02_Airstrip'), Status = 4, ObjectivesProgress = [1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_Chapter02.M_CH02_Airstrip:GetOrbitron'), SubObjectiveSets = [], GameStage = 3, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_Chapter03.M_Co_Ch03_Concordia'), Status = 4, ObjectivesProgress = [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 1, 1, 0, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_Chapter03.M_Co_Ch03_Concordia:ObjSet_33_FollowMoxxi'), SubObjectiveSets = [], GameStage = 5, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_Chapter04.M_Co_Chapter04'), Status = 4, ObjectivesProgress = [1, 3, 20, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 3, 1, 0, 1, 1, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_Chapter04.M_Co_Chapter04:ObjSet_GoToSprings'), SubObjectiveSets = [], GameStage = 6, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_Chapter05.M_Cork_WreckMain'), Status = 4, ObjectivesProgress = [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_Chapter05.M_Cork_WreckMain:AICore'), SubObjectiveSets = [], GameStage = 12, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Cork_DahlFactory_Plot.M_Cork_DahlFactory_Plot'), Status = 4, ObjectivesProgress = [1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 4, 1, 114, 1, 1, 1, 1, 1, 1, 12, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Cork_DahlFactory_Plot.M_Cork_DahlFactory_Plot:ObjSet_ReturnToMoxxi'), SubObjectiveSets = [], GameStage = 14, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Cork_HeliosFoothold_Plot.M_Cork_HeliosFoothold'), Status = 4, ObjectivesProgress = [1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Cork_HeliosFoothold_Plot.M_Cork_HeliosFoothold:Talk_to_Gladstone_TurnIn_Set'), SubObjectiveSets = [], GameStage = 16, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Cork_RandDFacility_Plot.M_Cork_RandDFacility'), Status = 4, ObjectivesProgress = [0, 3, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Cork_RandDFacility_Plot.M_Cork_RandDFacility:OS_150_TurnIn'), SubObjectiveSets = [], GameStage = 19, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Cork_InnerHull_Plot.M_Cork_InnerHull'), Status = 4, ObjectivesProgress = [1, 1, 1, 1, 1, 7, 56, 1, 1, 0, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Cork_InnerHull_Plot.M_Cork_InnerHull:TurnINSet'), SubObjectiveSets = [], GameStage = 21, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_LaserRebootMission.M_LaserRebootMission'), Status = 4, ObjectivesProgress = [1, 1, 1, 0, 7, 0, 1, 1, 1, 1, 1, 1, 1, 3, 1, 0, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_LaserRebootMission.M_LaserRebootMission:LaserBlowsUpSet'), SubObjectiveSets = [], GameStage = 24, bNeedsRewards = False, bHeardKickoff = True), 
        make_struct("MissionStatusPlayerData", MissionDef = find_object('MissionDefinition', 'GD_Co_Chapter11.M_DahlDigsite'), Status = 4, ObjectivesProgress = [1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], ActiveObjectiveSet = find_object('MissionObjectiveSetDefinition','GD_Co_Chapter11.M_DahlDigsite:ExitTheVaultSet'), SubObjectiveSets = [], GameStage = 26, bNeedsRewards = False, bHeardKickoff = True)
        ], 
        UnloadableDlcMissionData = [],
        SparkMissionData= [], 
        PendingMissionRewards = [],
        UnloadableDlcPendingMissionRewards= [],
        ActiveMission= 'GD_Co_Chapter11.M_DahlDigsite', 
        FilteredMissions= [], 
        VisitedTeleporters= ['Airstrip',
                            'Spaceport',
                            'MoonSurfaceFastTravel',
                            'ComFacility',
                            'Outlands', 
                            'WreckCrater', 
                            'DahlFactory', 
                            'DahlFactoryBossStart', 
                            'DahlFactoryBoss', 
                            'CentralTerminal', 
                            'RandDFacility', 
                            'JacksOffice', 
                            'Laser', 
                            'LaserBoss', 
                            'DigSite', 
                            'AccessShaft', 
                            'MoonCore'], 
                            LastVisitedTeleporter= 'Spaceport')

new_gladiator = make_struct("PlayerSaveData",
                            PlayerClassDefName="Gladiator",
                            ClassName=f"<font color='#FF6B2A'>BOOSTED GLADIATOR</font>",
                            CharacterName="Boosted Athena",
                            SaveGameFileId=-1,
                            )        
new_enforcer = make_struct("PlayerSaveData",
                            PlayerClassDefName="Enforcer",
                            ClassName=f"<font color='#FF6B2A'>BOOSTED ENFORCER</font>",
                            CharacterName="Boosted Wilhelm",
                            SaveGameFileId=-1,
                            )       
new_lawbringer = make_struct("PlayerSaveData",
                            PlayerClassDefName="Lawbringer",
                            ClassName=f"<font color='#FF6B2A'>BOOSTED LAWBRINGER</font>",
                            CharacterName="Boosted Nisha",
                            SaveGameFileId=-1,
                            )       
new_fragtrap = make_struct("PlayerSaveData",
                            PlayerClassDefName="Fragtrap",
                            ClassName=f"<font color='#FF6B2A'>BOOSTED FRAGTRAP</font>",
                            CharacterName="Boosted Claptrap",
                            SaveGameFileId=-1,
                            )       
new_doppelganger = make_struct("PlayerSaveData",
                            PlayerClassDefName="Doppelganger",
                            ClassName=f"<font color='#FF6B2A'>BOOSTED DOPPELGANGER</font>",
                            CharacterName="Boosted Jack",
                            SaveGameFileId=-1,
                            )       
new_baroness = make_struct("PlayerSaveData",
                            PlayerClassDefName="Baroness",
                            ClassName=f"<font color='#FF6B2A'>BOOSTED BARONESS</font>",
                            CharacterName="Boosted Aurelia",
                            SaveGameFileId=-1,
                            )
weapon_data = [
make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_Shotgun.A_Weapons.WT_Hyperion_Shotgun'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_Shotgun.A_Weapons.SG_Hyperion_3_Rare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Hyperion'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.Body.SG_Body_Hyperion_3'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.Grip.SG_Grip_Torgue'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.Barrel.SG_Barrel_Bandit'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.Sight.SG_Sight_None'), 
StockPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.Stock.SG_Stock_Bandit'), 
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.elemental.Shotgun_Elemental_Fire'), 
Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.Accessory.SG_Accessory_None'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Shotgun.ManufacturerMaterials.Mat_Hyperion_3'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Shotgun.Name.Prefix_Hyperion.Prefix_Elemental_Incendiary'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Shotgun.Name.Title_Hyperion.Title_Barrel_Bandit_TripleBarrel'), 
GameStage= 28,
UniqueId= 837484788), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_Launchers.A_Weapons.WT_Vladof_Launcher'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_Launchers.A_Weapons.RL_Vladof_3_Rare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Vladof'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.Body.L_Body_Vladof_3'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.Grip.L_Grip_Bandit'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.Barrel.L_Barrel_Maliwan'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.Sight.RL_Sight_Tediore'), 
StockPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.Exhaust.L_Exhaust_Tediore'), 
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.elemental.RL_Elemental_None'), 
Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.Accessory.RL_Accessory_TipCover_Damage'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Launchers.ManufacturerMaterials.Mat_Vladof_3'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Launchers.Name.Prefix_Vladof.Prefix_TipCover_Damage'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Launchers.Name.Title_Vladof.Title_Barrel_Maliwan_Radius'), 
GameStage= 28,
UniqueId= 251951720), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_AssaultRifle.A_Weapons.WT_Torgue_AssaultRifle'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_AssaultRifle.A_Weapons.AR_Torgue_3_Rare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Torgue'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Body.AR_Body_Torgue_3'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Grip.AR_Grip_Jakobs'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Barrel.AR_Barrel_Dahl'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Sight.AR_Sight_None'), 
StockPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Stock.AR_Stock_Vladof'), 
ElementalPartDefinition= None, Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Accessory.AR_Accessory_BanditClamp_Wild'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.ManufacturerMaterials.Mat_Torgue_3'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_AssaultRifle.Name.Prefix_Torgue.Prefix_BanditClamp_Wild'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_AssaultRifle.Name.Title_Torgue.Title_Barrel_Dahl_Carbine'), 
GameStage= 28,
UniqueId= 1657342196), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_SniperRifles.A_Weapons.WeaponType_Vladof_Sniper'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_SniperRifles.A_Weapons.Sniper_Vladof_3_Rare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Vladof'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.Body.SR_Body_Vladof_3'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.Grip.SR_Grip_Hyperion'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.Barrel.SR_Barrel_Hyperion'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.Sight.Sniper_Sight_Maliwan'), 
StockPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.Stock.SR_Stock_Dahl'), 
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.elemental.SR_Elemental_Ice'), 
Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.Accessory.Sniper_Accessory_Mount3_Damage'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SniperRifles.ManufacturerMaterials.Material_Vladof_3'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_SniperRifles.Name.Prefix_Vladof.Prefix_Mount3_Damage'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_SniperRifles.Name.Title_Vladof.Title_Barrel_Hyperion_Accurate'), 
GameStage= 28,
UniqueId= 564356330), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData', WeaponDefinitionData= make_struct('WeaponDefinitionData',
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_Pistol.A_Weapons.WeaponType_Hyperion_Pistol'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_Pistol.A_Weapons.Pistol_Hyperion_3_Rare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Hyperion'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Body.Pistol_Body_Hyperion_3'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Grip.Pistol_Grip_Torgue'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Barrel.Pistol_Barrel_Jakobs'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Sight.Pistol_Sight_None'), 
StockPartDefinition= None,
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.elemental.Pistol_Elemental_None'), 
Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Accessory.Pistol_Accessory_None'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.ManufacturerMaterials.Mat_Hyperion_3'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Shared_Names.Name.Prefix_Hyperion.Prefix_Grip_Torgue'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Pistol.Name.Title_Hyperion.Title_Barrel_Jakobs_SlowDamage'), 
GameStage= 28,
UniqueId= 1439119584), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_Pistol.A_Weapons.WeaponType_Maliwan_Pistol'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_Pistol.A_Weapons.Pistol_Maliwan_3_Rare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Maliwan'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Body.Pistol_Body_Maliwan_3'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Grip.Pistol_Grip_Bandit'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Barrel.Pistol_Barrel_Hyperion'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Sight.Pistol_Sight_None'), 
StockPartDefinition= None,
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.elemental.Pistol_Elemental_Corrosive'), 
Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.Accessory.Pistol_Accessory_Bayonet_1'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_Pistol.ManufacturerMaterials.Mat_Maliwan_3'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Pistol.Name.Prefix_Maliwan.Prefix_Bayonet_1'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_Pistol.Name.Title_Maliwan.Title_Barrel_Hyperion_Accurate'), 
GameStage= 28,
UniqueId= 247484158), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_SMG.A_Weapons.WT_SMG_Tediore'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_SMG.A_Weapons.SMG_Tediore_4_VeryRare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Tediore'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.Body.SMG_Body_Tediore_VarC'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.Grip.SMG_Grip_Maliwan'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.Barrel.SMG_Barrel_Hyperion'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.Sight.SMG_Sight_Dahl'), 
StockPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.Stock.SMG_Stock_Hyperion'), 
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.elemental.SMG_Elemental_None'), 
Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.Accessory.SMG_Accessory_Body2_Damage'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_SMG.ManufacturerMaterials.Mat_Tedior_4'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_SMG.Name.Prefix_Tediore.Prefix_Body2_Damage'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_SMG.Name.Title_Tediore.Title_Barrel_Hyperion_Accurate'), 
GameStage= 28,
UniqueId= 369697928), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Cork_Weap_Lasers.A_Weapons.WT_Tediore_Laser'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Cork_Weap_Lasers.A_Weapons.Laser_Tediore_4_VeryRare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Tediore'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Cork_Weap_Lasers.Body.Laser_Body_Tediore_4'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Cork_Weap_Lasers.FrontGrip.Laser_FrontGrip_Maliwan'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Cork_Weap_Lasers.Barrel.Laser_Barrel_Hyperion'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Cork_Weap_Lasers.Sight.Laser_Sight_Dahl'), 
StockPartDefinition= find_object('WeaponPartDefinition','GD_Cork_Weap_Lasers.Stock.Laser_Stock_Dahl'), 
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Cork_Weap_Lasers.elemental.Laser_Elemental_Corrosive'), 
Accessory1PartDefinition= None, Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Cork_Weap_Lasers.ManufacturerMaterials.Mat_Tediore_4'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Cork_Weap_Lasers.Name.Prefix_Tediore.Prefix_Corrosive'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Cork_Weap_Lasers.Name.Title_Tediore.Title_Barrel_Hyperion_Railgun'), 
GameStage= 28,
UniqueId= 509892648), 
Quickslot=0,
Mark=1,),

make_struct('WeaponSaveGameData',WeaponDefinitionData =make_struct('WeaponDefinitionData', 
WeaponTypeDefinition= find_object('WeaponTypeDefinition','GD_Weap_AssaultRifle.A_Weapons.WT_Vladof_AssaultRifle'), 
BalanceDefinition= find_object('WeaponBalanceDefinition','GD_Weap_AssaultRifle.A_Weapons.AR_Vladof_3_Rare'), 
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Vladof'), 
ManufacturerGradeIndex= 28, 
BodyPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Body.AR_Body_Vladof_3'), 
GripPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Grip.AR_Grip_Bandit'), 
BarrelPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Barrel.AR_Barrel_Bandit'), 
SightPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Sight.AR_Sight_Jakobs'), 
StockPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Stock.AR_Stock_Vladof'), 
ElementalPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.elemental.AR_Elemental_None'), 
Accessory1PartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.Accessory.AR_Accessory_Foregrip_Stability'), 
Accessory2PartDefinition= find_object('WeaponPartDefinition','GD_Weap_Accessories.Moonstone.Moonstone_Attachment_None'), 
MaterialPartDefinition= find_object('WeaponPartDefinition','GD_Weap_AssaultRifle.ManufacturerMaterials.Mat_Vladof_3'), 
PrefixPartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_AssaultRifle.Name.Prefix_Vladof.Prefix_Foregrip_Stability'), 
TitlePartDefinition= find_object('WeaponNamePartDefinition','GD_Weap_AssaultRifle.Name.Title.Title_Rifle'), 
GameStage= 28,
UniqueId= 139593634), 
Quickslot=0,
Mark=1,),
]

def get_item_data():
    return [
make_struct("InventorySaveGameData",DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ClassModDefinition",'GD_Quince_ClassMods.A_Item_Doppelganger.ClassMod_Doppelganger_Economist'),
BalanceDefinition= find_object('ClassModBalanceDefinition','GD_Quince_ItemGrades.ClassMods.BalDef_ClassMod_Doppelganger_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Hyperion'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.Specialization.Spec_AS1_BS3'),
BetaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary.PrimaryStat_A0_B0_C0'),
GammaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary02.PrimaryStat02_A0_B3_C0'),
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPenalty.StatPenalty_A0_B0_C4'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Quince_ClassMods.Prefix_Doppelganger.Prefix_Economist_01_Monetary'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods.Title.Title_ClassMod'),
GameStage= 28,
UniqueId= 1341405387),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ClassModDefinition",'GD_Cork_ClassMods.A_Item_Lawbringer.ClassMod_Lawbringer_Rustler'),
BalanceDefinition= find_object('ClassModBalanceDefinition','GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Lawbringer_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Torgue'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.Specialization.Spec_AS1_BS3'),
BetaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary.PrimaryStat_A4_B0_C0'),
GammaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary02.PrimaryStat02_A0_B5_C0'),
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPenalty.StatPenalty_A0_B0_C1'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods.Prefix_Lawbringer.Prefix_Rustler_01_Snappy'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods.Title.Title_ClassMod'),
GameStage= 28,
UniqueId= 1798262290),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ClassModDefinition",'Crocus_ClassMods.A_Item_Baroness.ClassMod_Baroness_Queen'),
BalanceDefinition= find_object('ClassModBalanceDefinition','GD_Crocus_ItemGrades.ClassMods.BalDef_ClassMod_Baroness_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Hyperion'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.Specialization.Spec_AS1_BS2'),
BetaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary.PrimaryStat_A5_B0_C0'),
GammaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary02.PrimaryStat02_A0_B1_C0'),
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPenalty.StatPenalty_A0_B0_C3'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','Crocus_ClassMods.Prefix_Baroness.Prefix_Queen_01_Ice'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods.Title.Title_ClassMod'),
GameStage= 28,
UniqueId= 718611704),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ClassModDefinition",'GD_Cork_ClassMods_SMJ.A_Item_Enforcer.ClassMod_Enforcer_Fighter'),
BalanceDefinition= find_object('ClassModBalanceDefinition','GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Enforcer_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Hyperion'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.Specialization.Spec_AS2_BS1'),
BetaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary.PrimaryStat_A5_B0_C0'),
GammaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary02.PrimaryStat02_A0_B3_C0'),
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPenalty.StatPenalty_A0_B0_C2'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods_SMJ.Prefix_Enforcer.Prefix_Fighter_02_Fighter-Bomber'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods.Title.Title_ClassMod'),
GameStage= 28,
UniqueId= 1917404986),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ClassModDefinition",'GD_Cork_ClassMods_TW.A_Item_Prototype.ClassMod_Prototype_Overclocker'),
BalanceDefinition= find_object('ClassModBalanceDefinition','GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Prototype_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Dahl'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.Specialization.Spec_AS3_BS1'),
BetaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary.PrimaryStat_A0_B0_C0'),
GammaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary02.PrimaryStat02_A0_B2_C0'),
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPenalty.StatPenalty_A0_B0_C2'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods_TW.Prefix_Prototype.Prefix_Overclocker_03_Unstable'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods.Title.Title_ClassMod'),
GameStage= 28,
UniqueId= 268455251),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ClassModDefinition",'GD_Cork_ClassMods_SMJ.A_Item_Gladiator.ClassMod_Gladiator_Dragon'),
BalanceDefinition= find_object('ClassModBalanceDefinition','GD_Cork_ItemGrades.ClassMods.BalDef_ClassMod_Gladiator_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Maliwan'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.Specialization.Spec_AS3_BS1'),
BetaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary.PrimaryStat_A0_B0_C0'),
GammaItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPrimary02.PrimaryStat02_A0_B3_C0'),
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ClassModPartDefinition','GD_Cork_ClassMods.StatPenalty.StatPenalty_A0_B0_C3'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods_SMJ.Prefix_Gladiator.Prefix_Dragon_03_Marauding'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Cork_ClassMods.Title.Title_ClassMod'),
GameStage= 28,
UniqueId= 1010829612),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ShieldDefinition",'GD_Shields.A_Item.Shield_Absorption'),
BalanceDefinition= find_object('InventoryBalanceDefinition','GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Absorption_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Vladof'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Body.Body8_Pangolin'),
BetaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Battery.Battery7_Hyperion'),
GammaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Capacitor.Capacitor3_Vladof'),
DeltaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Accessory.Accessory3_Absorption'),
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Material.Material3_Rare_Absorption'),
PrefixItemNamePartDefinition= None,
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Shields.Titles.Title_Absorption01_AbsorptionShield'),
GameStage= 28,
UniqueId= 1784183129),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ShieldDefinition",'GD_Shields.A_Item.Shield_Booster'),
BalanceDefinition= find_object('InventoryBalanceDefinition','GD_ItemGrades.Shields.ItemGrade_Gear_Shield_Booster_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Dahl'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Body.Body6_Torgue'),
BetaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Battery.Battery2_Bandit'),
GammaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Capacitor.Capacitor3_Vladof'),
DeltaItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Accessory.Accessory4_Booster'),
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= None,
ThetaItemPartDefinition= None,
MaterialItemPartDefinition= find_object('ShieldPartDefinition','GD_Shields.Material.Material3_Rare_Booster'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Shields.Prefixes.Prefix_Rate_Dahl03'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_Shields.Titles.Title_Booster01_BoosterShield'),
GameStage= 28,
UniqueId= 202853139),
Quantity= 1,
bEquipped= False,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ArtifactDefinition",'GD_MoonItems.A_Item.MoonItem_Bomber'),
BalanceDefinition= find_object('InventoryBalanceDefinition','GD_MoonItems.BalanceDefinitions.A_Bomber_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Torgue'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ArtifactPartDefinition','GD_MoonItems.EnableSpecial.EnableSpecial_ElementNone'),
BetaItemPartDefinition= None,
GammaItemPartDefinition= None,
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= find_object('ArtifactPartDefinition','GD_MoonItems.Body.Body_Bomber'),
ThetaItemPartDefinition= find_object('ArtifactPartDefinition','GD_MoonItems.Upgrade.Upgrade_Grade8'),
MaterialItemPartDefinition= None,
PrefixItemNamePartDefinition= None,
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_MoonItems.Titles.Title_Bomber'),
GameStage= 28,
UniqueId= 2021070285),
Quantity= 1,
bEquipped= False,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("ArtifactDefinition",'GD_MoonItems.A_Item.MoonItem_Acrobat'),
BalanceDefinition= find_object('InventoryBalanceDefinition','GD_MoonItems.BalanceDefinitions.A_Acrobat_03_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Vladof'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('ArtifactPartDefinition','GD_MoonItems.EnableSpecial.EnableSpecial_Element4'),
BetaItemPartDefinition= None,
GammaItemPartDefinition= None,
DeltaItemPartDefinition= None,
EpsilonItemPartDefinition= None,
ZetaItemPartDefinition= None,
EtaItemPartDefinition= find_object('ArtifactPartDefinition','GD_MoonItems.Body.Body_Acrobat'),
ThetaItemPartDefinition= find_object('ArtifactPartDefinition','GD_MoonItems.Upgrade.Upgrade_Grade9'),
MaterialItemPartDefinition= None,
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_MoonItems.Prefixes.Prefix_Element_Ice01'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_MoonItems.Titles.Title_Acrobat'),
GameStage= 28,
UniqueId= 1878146830),
Quantity= 1,
bEquipped= True,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("GrenadeModDefinition",'GD_GrenadeMods.A_Item.GrenadeMod_Standard'),
BalanceDefinition= find_object('InventoryBalanceDefinition','GD_GrenadeMods.A_Item.GM_Transfusion_3_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Maliwan'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Payload.Payload_Transfusion_AirMask'),
BetaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Delivery.Delivery_Lob_Sticky'),
GammaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Trigger.Trigger_Grade0'),
DeltaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Accessory.Accessory_Explosive'),
EpsilonItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Damage.Damage_Grade5'),
ZetaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.DamageRadius.DamageRadius_Large'),
EtaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.ChildCount.ChildCount_Grade3'),
ThetaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.StatusDamage.StatusDamage_Grade2'),
MaterialItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Material.Material_Maliwan_3_Rare'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_GrenadeMods.Prefix.Prefix_Lob_Sticky'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_GrenadeMods.Title.Title_TransfusionExplosive'),
GameStage= 28,
UniqueId= 1529556586),
Quantity= 1,
bEquipped= False,
Mark= 1),

make_struct("InventorySaveGameData",
DefinitionData= make_struct("ItemDefinitionData",
ItemDefinition= find_object("GrenadeModDefinition",'GD_GrenadeMods.A_Item.GrenadeMod_Standard'),
BalanceDefinition= find_object('InventoryBalanceDefinition','GD_GrenadeMods.A_Item.GM_AreaEffect_3_Rare'),
ManufacturerDefinition= find_object('ManufacturerDefinition','GD_Manufacturers.Manufacturers.Vladof'),
ManufacturerGradeIndex= 28,
AlphaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Payload.Payload_AreaEffect'),
BetaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Delivery.Delivery_LongBow'),
GammaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Trigger.Trigger_Grade1'),
DeltaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Accessory.Accessory_Shock_Grade4'),
EpsilonItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Damage.Damage_Grade4'),
ZetaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.DamageRadius.DamageRadius_Small'),
EtaItemPartDefinition= None,
ThetaItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.StatusDamage.StatusDamage_Grade1'),
MaterialItemPartDefinition= find_object('GrenadeModPartDefinition','GD_GrenadeMods.Material.Material_Vladof_3_Rare'),
PrefixItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_GrenadeMods.Prefix.Prefix_Longbow'),
TitleItemNamePartDefinition= find_object('ItemNamePartDefinition','GD_GrenadeMods.Title.Title_AreaEffectShock'),
GameStage= 28,
UniqueId= 212950691),
Quantity= 1,
bEquipped= True,
Mark= 1),

]